INSERT INTO webshop.labels (name, slugname)
VALUES ('A', 'A'),
       ('A.F.C.A', 'AFCA'),
       ('A.P.C.Absolut Joy', 'APCAbsolutJoy'),
       ('Acne Studios', 'AcneStudios'),
       ('Acqua Limone', 'AcquaLimone'),
       ('Add', 'Add'),
       ('adidas', 'adidas'),
       ('adidas Originals', 'adidasOriginals'),
       ('Advanta', 'Advanta'),
       ('Aglini', 'Aglini'),
       ('Aimé Leon Dore', 'AiméLeonDore'),
       ('AKOO', 'AKOO'),
       ('Alaia', 'Alaia'),
       ('Alain Figaret', 'AlainFigaret'),
       ('Alberta Ferretti', 'AlbertaFerretti'),
       ('Alessandro Dell´Acqua', 'AlessandroDell´Acqua'),
       ('Alessi', 'Alessi'),
       ('AlexaChung', 'AlexaChung'),
       ('Alexander McQueen', 'AlexanderMcQueen'),
       ('Alexander Wang', 'AlexanderWang'),
       ('Alice & Olivia', 'AliceOlivia'),
       ('AllSaints', 'AllSaints'),
       ('Alpha Studio', 'AlphaStudio'),
       ('Altuzarra', 'Altuzarra'),
       ('Alysi', 'Alysi'),
       ('American Eagle Outfitters', 'AmericanEagleOutfitters'),
       ('Americanflat', 'Americanflat'),
       ('Ami', 'Ami'),
       ('André Kim', 'AndréKim'),
       ('Ann Demeulemeester', 'AnnDemeulemeester'),
       ('Annarita N.', 'AnnaritaN'),
       ('Anne Fontaine', 'AnneFontaine'),
       ('Anne T. Hill', 'AnneTHill'),
       ('Anthropologie', 'Anthropologie'),
       ('Antony Morato', 'AntonyMorato'),
       ('Antthony Mark Hankins', 'AntthonyMarkHankins'),
       ('Anya Hindmarch', 'AnyaHindmarch'),
       ('Apalis', 'Apalis'),
       ('Aquazzura', 'Aquazzura'),
       ('Arckiv', 'Arckiv'),
       ('Armani', 'Armani'),
       ('Armoire Officielle', 'ArmoireOfficielle'),
       ('Arthur Galan AG', 'ArthurGalanAG'),
       ('Artopweb', 'Artopweb'),
       ('artPause', 'artPause'),
       ('Arty Pie', 'ArtyPie'),
       ('Ash', 'Ash'),
       ('Asics', 'Asics'),
       ('Asos', 'Asos'),
       ('Asos Petite', 'AsosPetite'),
       ('Aspesi', 'Aspesi'),
       ('AT.P. CO', 'ATPCO'),
       ('Atos Lombardini', 'AtosLombardini'),
       ('Bailey 44', 'Bailey44'),
       ('Balenciaga', 'Balenciaga'),
       ('Ballantyne', 'Ballantyne'),
       ('Bally', 'Bally'),
       ('Balmain', 'Balmain'),
       ('Banana Moon', 'BananaMoon'),
       ('Barba', 'Barba'),
       ('Barena', 'Barena'),
       ('Barneys New York', 'BarneysNewYork'),
       ('Bellerose', 'Bellerose'),
       ('Bellerose Belgium', 'BelleroseBelgium'),
       ('Belstaff', 'Belstaff'),
       ('Ben Sherman', 'BenSherman'),
       ('BenchBenetton', 'BenchBenetton'),
       ('Berna', 'Berna'),
       ('Berwich', 'Berwich'),
       ('Bestseller', 'Bestseller'),
       ('Betty Barclay', 'BettyBarclay'),
       ('Biba Apparels', 'BibaApparels'),
       ('Big Art Shop', 'BigArtShop'),
       ('Big Box Art', 'BigBoxArt'),
       ('Bigotti', 'Bigotti'),
       ('BILLIEBLUSH', 'BILLIEBLUSH'),
       ('Birkenstock', 'Birkenstock'),
       ('Blanc & Eclare', 'BlancEclare'),
       ('Blauer', 'Blauer'),
       ('Blaze of Sweden', 'BlazeofSweden'),
       ('Blend', 'Blend'),
       ('Bllack Noir', 'BllackNoir'),
       ('Bloch', 'Bloch'),
       ('Blue Les Copains', 'BlueLesCopains'),
       ('Bluenotes', 'Bluenotes'),
       ('Blugirl', 'Blugirl'),
       ('Blumarine', 'Blumarine'),
       ('Boglioli', 'Boglioli'),
       ('Bonia', 'Bonia'),
       ('Bosideng', 'Bosideng'),
       ('BOSS', 'BOSS'),
       ('Bottega Veneta', 'BottegaVeneta'),
       ('Boxfresh', 'Boxfresh'),
       ('BP Studio', 'BPStudio'),
       ('Brave Soul', 'BraveSoul'),
       ('Brax', 'Brax'),
       ('Brian Dales', 'BrianDales'),
       ('Brooks Brothers', 'BrooksBrothers'),
       ('Brooksfield', 'Brooksfield'),
       ('Brunello Cucinelli', 'BrunelloCucinelli'),
       ('Buffalo', 'Buffalo'),
       ('Bugatti', 'Bugatti'),
       ('Burberry', 'Burberry'),
       ('Byblos', 'Byblos'),
       ('C&A', 'CA'),
       ('Cafènoir', 'Cafènoir'),
       ('Caliban', 'Caliban'),
       ('Callisti', 'Callisti'),
       ('Calvin Klein', 'CalvinKlein'),
       ('CALVIN KLEIN 205W39NYC', 'CALVINKLEIN205W39NYC'),
       ('Camel Active', 'CamelActive'),
       ('Camper', 'Camper'),
       ('Canali', 'Canali'),
       ('Cantarelli', 'Cantarelli'),
       ('Canterbury of New Zealand', 'CanterburyofNewZealand'),
       ('Caraceni', 'Caraceni'),
       ('Carbrini Sportswear', 'CarbriniSportswear'),
       ('Carhartt Work in Progress', 'CarharttWorkinProgress'),
       ('Carla G.', 'CarlaG'),
       ('Carlo Palazzi', 'CarloPalazzi'),
       ('Carven', 'Carven'),
       ('Casadei', 'Casadei'),
       ('Cassidi', 'Cassidi'),
       ('Castro', 'Castro'),
       ('Catherine Lansfield', 'CatherineLansfield'),
       ('Catimini', 'Catimini'),
       ('Celine', 'Celine'),
       ('Cesare PaciottiChanel', 'CesarePaciottiChanel'),
       ('Charlotte Olympia', 'CharlotteOlympia'),
       ('Cheap Monday', 'CheapMonday'),
       ('Chervo', 'Chervo'),
       ('Chiara Ferragni', 'ChiaraFerragni'),
       ('China Heilan Group', 'ChinaHeilanGroup'),
       ('Chloé', 'Chloé'),
       ('Christian Louboutin', 'ChristianLouboutin'),
       ('Christopher Kane', 'ChristopherKane'),
       ('Clarks', 'Clarks'),
       ('Closed', 'Closed'),
       ('Coach', 'Coach'),
       ('Cockpit USA', 'CockpitUSA'),
       ('Colmar', 'Colmar'),
       ('Comma', 'Comma'),
       ('Comme Des Garçons', 'CommeDesGarçons'),
       ('Comptoir des Cotonniers', 'ComptoirdesCotonniers'),
       ('Converse', 'Converse'),
       ('CornelianiCostume National', 'CornelianiCostumeNational'),
       ('Countess Mara', 'CountessMara'),
       ('CristinaeEffe', 'CristinaeEffe'),
       ('Croc O'' Shirt', 'CrocOShirt'),
       ('Crocs', 'Crocs'),
       ('Cruciani', 'Cruciani'),
       ('Cult', 'Cult'),
       ('Cuplé', 'Cuplé'),
       ('Current Elliott', 'CurrentElliott'),
       ('Cycle', 'Cycle'),
       ('Céline', 'Céline'),
       ('Dale of Norway', 'DaleofNorway'),
       ('Damani Dada', 'DamaniDada'),
       ('Daniel Hechter', 'DanielHechter'),
       ('Daniele Alessandrini', 'DanieleAlessandrini'),
       ('Daniele Fiesoli', 'DanieleFiesoli'),
       ('DC Comics', 'DCComics'),
       ('Deha', 'Deha'),
       ('Deknudt Frames', 'DeknudtFrames'),
       ('Deko Trends', 'DekoTrends'),
       ('Dekoria', 'Dekoria'),
       ('Denby', 'Denby'),
       ('Denver Hayes', 'DenverHayes'),
       ('Department 5', 'Department5'),
       ('Derek Lam', 'DerekLam'),
       ('Design Vicenza', 'DesignVicenza'),
       ('DesigualDiadora', 'DesigualDiadora'),
       ('Diane Von Fürstenberg', 'DianeVonFürstenberg'),
       ('Dickies', 'Dickies'),
       ('DieselDior', 'DieselDior'),
       ('Dirk Bikkembergs', 'DirkBikkembergs'),
       ('Disney', 'Disney'),
       ('DKNY', 'DKNY'),
       ('Dockers by Gerli', 'DockersbyGerli'),
       ('Dolce & Gabbana', 'DolceGabbana'),
       ('Dolfin Swimwear', 'DolfinSwimwear'),
       ('Domenico Tagliente', 'DomenicoTagliente'),
       ('Dondup', 'Dondup'),
       ('Doppiaa', 'Doppiaa'),
       ('Dorothee Schumacher', 'DorotheeSchumacher'),
       ('Dorothy Perkins', 'DorothyPerkins'),
       ('Doucal''s', 'Doucals'),
       ('Douceur d''Intérieur', 'DouceurdIntérieur'),
       ('Douuod', 'Douuod'),
       ('Dr. Martens', 'DrMartens'),
       ('Draft:Kidbox', 'Draft:Kidbox'),
       ('Dries Van Noten', 'DriesVanNoten'),
       ('Drumohr', 'Drumohr'),
       ('Dsquared2', 'Dsquared2'),
       ('Dsquared2 Kids', 'Dsquared2Kids'),
       ('Duchamp', 'Duchamp'),
       ('Dutch Decor', 'DutchDecor'),
       ('Duvelleroy', 'Duvelleroy'),
       ('Duvetica', 'Duvetica'),
       ('Dwell', 'Dwell'),
       ('Eastpak', 'Eastpak'),
       ('Ebarrito', 'Ebarrito'),
       ('Ecco', 'Ecco'),
       ('EDC by Esprit', 'EDCbyEsprit'),
       ('EDUN', 'EDUN'),
       ('Edwin', 'Edwin'),
       ('Eglo', 'Eglo'),
       ('Eiffel Textile', 'EiffelTextile'),
       ('El Naturalista', 'ElNaturalista'),
       ('Elaine Kim', 'ElaineKim'),
       ('Eleventy', 'Eleventy'),
       ('Elie Tahari', 'ElieTahari'),
       ('Elisabetta Franchi', 'ElisabettaFranchi'),
       ('Elizabeth & James', 'ElizabethJames'),
       ('Ellery', 'Ellery'),
       ('Elsa Schiaparelli', 'ElsaSchiaparelli'),
       ('Emanuel Ungaro', 'EmanuelUngaro'),
       ('Emanuela Passeri', 'EmanuelaPasseri'),
       ('Emilia Lay', 'EmiliaLay'),
       ('Emilio Pucci', 'EmilioPucci'),
       ('Emporio Armani', 'EmporioArmani'),
       ('Emsa', 'Emsa'),
       ('English Eccentrics', 'EnglishEccentrics'),
       ('Entre Amis', 'EntreAmis'),
       ('Enza Costa', 'EnzaCosta'),
       ('Equipment', 'Equipment'),
       ('Erdem', 'Erdem'),
       ('Eres', 'Eres'),
       ('Erika Cavallini Semi Couture', 'ErikaCavalliniSemiCouture'),
       ('Ermanno Scervino', 'ErmannoScervino'),
       ('Ermenegildo Zegna', 'ErmenegildoZegna'),
       ('Escada', 'Escada'),
       ('Esprit', 'Esprit'),
       ('Essentiel', 'Essentiel'),
       ('Ethan James', 'EthanJames'),
       ('Ethika', 'Ethika'),
       ('Eton', 'Eton'),
       ('Etro', 'Etro'),
       ('Eurographics', 'Eurographics'),
       ('European Culture', 'EuropeanCulture'),
       ('EVANS', 'EVANS'),
       ('Excelsa', 'Excelsa'),
       ('Exclusive Home Curtains', 'ExclusiveHomeCurtains'),
       ('Exotic India', 'ExoticIndia'),
       ('Extè', 'Extè'),
       ('Eyelevel', 'Eyelevel'),
       ('Eysa', 'Eysa'),
       ('Fabi', 'Fabi'),
       ('Fabiana Filippi', 'FabianaFilippi'),
       ('Fackelmann', 'Fackelmann'),
       ('Faith Connexion', 'FaithConnexion'),
       ('Falke', 'Falke'),
       ('Fashion for Home', 'FashionforHome'),
       ('Fashion line', 'Fashionline'),
       ('Fat Face', 'FatFace'),
       ('FAUSTO PUGLISI', 'FAUSTOPUGLISI'),
       ('Fay', 'Fay'),
       ('Febland Group', 'FeblandGroup'),
       ('Fenchurch', 'Fenchurch'),
       ('FendiFenty Puma by Rihanna', 'FendiFentyPumabyRihanna'),
       ('Ferdinando Sarmi', 'FerdinandoSarmi'),
       ('Ferm Living', 'FermLiving'),
       ('Fila', 'Fila'),
       ('FILIPPO DE LAURENTIIS', 'FILIPPODELAURENTIIS'),
       ('Final Touch Interior Decor', 'FinalTouchInteriorDecor'),
       ('Firetrap', 'Firetrap'),
       ('First People First', 'FirstPeopleFirst'),
       ('Fisico', 'Fisico'),
       ('FitFlop', 'FitFlop'),
       ('Flash Furniture', 'FlashFurniture'),
       ('Fleur du Mal', 'FleurduMal'),
       ('Fleuresse', 'Fleuresse'),
       ('FLY London', 'FLYLondon'),
       ('Forever Lazy', 'ForeverLazy'),
       ('Fornarina', 'Fornarina'),
       ('Fornasetti', 'Fornasetti'),
       ('Forte_Forte', 'Forte_Forte'),
       ('Fossil', 'Fossil'),
       ('Fox', 'Fox'),
       ('Fradi', 'Fradi'),
       ('Frame Company', 'FrameCompany'),
       ('Frame Denim', 'FrameDenim'),
       ('Frames by Post', 'FramesbyPost'),
       ('Frankie Morello', 'FrankieMorello'),
       ('Franklin & Marshall', 'FranklinMarshall'),
       ('Fred Mello', 'FredMello'),
       ('Fred Perry', 'FredPerry'),
       ('Fred´s World By Green Cotton', 'Fred´sWorldByGreenCotton'),
       ('Free People', 'FreePeople'),
       ('French Connection', 'FrenchConnection'),
       ('Furla', 'Furla'),
       ('G-Star', 'G-Star'),
       ('G-Star Raw', 'G-StarRaw'),
       ('G2000', 'G2000'),
       ('Gabor', 'Gabor'),
       ('Gabs', 'Gabs'),
       ('Ganni', 'Ganni'),
       ('GANTGanter', 'GANTGanter'),
       ('Garage', 'Garage'),
       ('Garanimals', 'Garanimals'),
       ('Garcia', 'Garcia'),
       ('Garcia de Pou', 'GarciadePou'),
       ('Gas', 'Gas'),
       ('Gattinoni', 'Gattinoni'),
       ('Gaudì', 'Gaudì'),
       ('Gaëlle Paris', 'GaëlleParis'),
       ('GB Eye Limited', 'GBEyeLimited'),
       ('GCDS', 'GCDS'),
       ('Gebrüder Stitch', 'GebrüderStitch'),
       ('Genny', 'Genny'),
       ('Gentryportofino', 'Gentryportofino'),
       ('George J. Love', 'GeorgeJLove'),
       ('Geox', 'Geox'),
       ('Gerry Weber', 'GerryWeber'),
       ('Giambattista Valli', 'GiambattistaValli'),
       ('Giancarlo Paoli', 'GiancarloPaoli'),
       ('Gianvito Rossi', 'GianvitoRossi'),
       ('Giesswein', 'Giesswein'),
       ('Giorgia & Johns', 'GiorgiaJohns'),
       ('Giorgio Armani', 'GiorgioArmani'),
       ('Gioseppo', 'Gioseppo'),
       ('Giuseppe Zanotti', 'GiuseppeZanotti'),
       ('Givenchy', 'Givenchy'),
       ('Glamorous', 'Glamorous'),
       ('Globo Lighting', 'GloboLighting'),
       ('Gloria Vanderbilt', 'GloriaVanderbilt'),
       ('Go International', 'GoInternational'),
       ('Golden Goose', 'GoldenGoose'),
       ('Gotha', 'Gotha'),
       ('Gran Sasso', 'GranSasso'),
       ('Grishko', 'Grishko'),
       ('GRUND', 'GRUND'),
       ('GTA', 'GTA'),
       ('Gucci', 'Gucci'),
       ('Gucci Kids', 'GucciKids'),
       ('Guess', 'Guess'),
       ('Guglielminotti', 'Guglielminotti'),
       ('Gunhild', 'Gunhild'),
       ('Gunne Sax', 'GunneSax'),
       ('Gunze', 'Gunze'),
       ('Gözze', 'Gözze'),
       ('H&M', 'HM'),
       ('Hackett', 'Hackett'),
       ('Haider Ackermann', 'HaiderAckermann'),
       ('Haikure', 'Haikure'),
       ('Haku Möbel', 'HakuMöbel'),
       ('Halston Heritage', 'HalstonHeritage'),
       ('Hamaki-Ho', 'Hamaki-Ho'),
       ('Han Kjøbenhavn', 'HanKjøbenhavn'),
       ('Hanita', 'Hanita'),
       ('Hanro', 'Hanro'),
       ('Happiness Brand', 'HappinessBrand'),
       ('Harmont & Blaine', 'HarmontBlaine'),
       ('Harris Wharf London', 'HarrisWharfLondon'),
       ('Hartford', 'Hartford'),
       ('HatleyHaus Alkire', 'HatleyHausAlkire'),
       ('Havaianas', 'Havaianas'),
       ('Helmut LangHEMA', 'HelmutLangHEMA'),
       ('Henry Cotton´s', 'HenryCotton´s'),
       ('Heritage', 'Heritage'),
       ('Hermès', 'Hermès'),
       ('Herno', 'Herno'),
       ('Herschel', 'Herschel'),
       ('Hervé Leger', 'HervéLeger'),
       ('Hield', 'Hield'),
       ('High', 'High'),
       ('High Street Design', 'HighStreetDesign'),
       ('Historic', 'Historic'),
       ('Hogan', 'Hogan'),
       ('Hollyberry HomeHOME MAISON', 'HollyberryHomeHOMEMAISON'),
       ('Honigman', 'Honigman'),
       ('Honsel Leuchten', 'HonselLeuchten'),
       ('Hope Collection', 'HopeCollection'),
       ('HTC', 'HTC'),
       ('HTnaturals', 'HTnaturals'),
       ('Huber', 'Huber'),
       ('Hudson', 'Hudson'),
       ('HUGO BOSS', 'HUGOBOSS'),
       ('Hummel', 'Hummel'),
       ('Husky', 'Husky'),
       ('Hydrogen', 'Hydrogen'),
       ('Hérve Léger', 'HérveLéger'),
       ('Högl', 'Högl'),
       ('I Saw It First', 'ISawItFirst'),
       ('I''m Brian', 'ImBrian'),
       ('I''m Isola Marras', 'ImIsolaMarras'),
       ('I. & R. Morley', 'IRMorley'),
       ('Ian Snow', 'IanSnow'),
       ('IANUX', 'IANUX'),
       ('Ibili', 'Ibili'),
       ('iBlues', 'iBlues'),
       ('Iceberg', 'Iceberg'),
       ('Ichi', 'Ichi'),
       ('Icone', 'Icone'),
       ('Igi & Co', 'IgiCo'),
       ('Ih Nom Uh Nit', 'IhNomUhNit'),
       ('iittala', 'iittala'),
       ('Il Gufo', 'IlGufo'),
       ('Imperfect', 'Imperfect'),
       ('Imperial', 'Imperial'),
       ('Impressions', 'Impressions'),
       ('Incotex', 'Incotex'),
       ('Individual', 'Individual'),
       ('Ingram', 'Ingram'),
       ('Inov8', 'Inov8'),
       ('Inside', 'Inside'),
       ('Inspired Walls', 'InspiredWalls'),
       ('InterDesign', 'InterDesign'),
       ('Intropia', 'Intropia'),
       ('Invicta', 'Invicta'),
       ('IRIS & INK', 'IRISINK'),
       ('Iro', 'Iro'),
       ('Iron Heart', 'IronHeart'),
       ('Irregular Choice', 'IrregularChoice'),
       ('Isa Arfen', 'IsaArfen'),
       ('Isabel Benenato', 'IsabelBenenato'),
       ('Isabel Marant', 'IsabelMarant'),
       ('Isaia', 'Isaia'),
       ('ISC', 'ISC'),
       ('ISKO', 'ISKO'),
       ('Islo Isabella Lorusso', 'IsloIsabellaLorusso'),
       ('Issa', 'Issa'),
       ('Issey Miyake', 'IsseyMiyake'),
       ('Italian Bed Linen', 'ItalianBedLinen'),
       ('Italo Ottinetti', 'ItaloOttinetti'),
       ('Ivories', 'Ivories'),
       ('Izod Lacoste', 'IzodLacoste'),
       ('J Brand', 'JBrand'),
       ('J-Wear', 'J-Wear'),
       ('J.Lindeberg', 'JLindeberg'),
       ('J.W. SAX Milano', 'JWSAXMilano'),
       ('J.W.Anderson', 'JWAnderson'),
       ('Jack & Jones', 'JackJones'),
       ('Jacob Cohen', 'JacobCohen'),
       ('Jako', 'Jako'),
       ('James & Nicholson', 'JamesNicholson'),
       ('James Perse', 'JamesPerse'),
       ('Janet & Janet', 'JanetJanet'),
       ('Jean Machine', 'JeanMachine'),
       ('Jean Paul Gaultier', 'JeanPaulGaultier'),
       ('Jeckerson', 'Jeckerson'),
       ('Jeffrey Campbell', 'JeffreyCampbell'),
       ('Jenny Hellström', 'JennyHellström'),
       ('Jennyfer', 'Jennyfer'),
       ('Jeordie''s', 'Jeordies'),
       ('Jigsaw', 'Jigsaw'),
       ('Jijil', 'Jijil'),
       ('Jijil Jolie', 'JijilJolie'),
       ('Jil Sander', 'JilSander'),
       ('Jimmy Choo London', 'JimmyChooLondon'),
       ('Joe Browns', 'JoeBrowns'),
       ('Joe Fresh', 'JoeFresh'),
       ('John Galliano', 'JohnGalliano'),
       ('JOHN GALLIANO KIDS', 'JOHNGALLIANOKIDS'),
       ('John Richmond', 'JohnRichmond'),
       ('John Varvatos', 'JohnVarvatos'),
       ('John Weitz', 'JohnWeitz'),
       ('Joie', 'Joie'),
       ('Jolie By Edward Spiers', 'JolieByEdwardSpiers'),
       ('Jon Richard', 'JonRichard'),
       ('Jonathan Simkhai', 'JonathanSimkhai'),
       ('Joop', 'Joop'),
       ('Josef Seibel', 'JosefSeibel'),
       ('JosephJoshua Sanders', 'JosephJoshuaSanders'),
       ('Joules', 'Joules'),
       ('Joykeep Jeans', 'JoykeepJeans'),
       ('Jucca', 'Jucca'),
       ('Judge', 'Judge'),
       ('Julian Bowen', 'JulianBowen'),
       ('Junya Watanabe', 'JunyaWatanabe'),
       ('Just Cavalli', 'JustCavalli'),
       ('Just Contempo', 'JustContempo'),
       ('JUSTyou', 'JUSTyou'),
       ('K-Way', 'K-Way'),
       ('Kahla', 'Kahla'),
       ('KAISER', 'KAISER'),
       ('Kalliste', 'Kalliste'),
       ('Kangaroos', 'Kangaroos'),
       ('Kangra Cashmere', 'KangraCashmere'),
       ('Kanz', 'Kanz'),
       ('Kaos', 'Kaos'),
       ('Kaporal', 'Kaporal'),
       ('Kappa', 'Kappa'),
       ('Karen Millen', 'KarenMillen'),
       ('Karl Kani', 'KarlKani'),
       ('Karl Lagerfeld', 'KarlLagerfeld'),
       ('Kartell', 'Kartell'),
       ('Katia G.', 'KatiaG'),
       ('KELA', 'KELA'),
       ('KEN BARRELL', 'KENBARRELL'),
       ('Ken Done', 'KenDone'),
       ('Kendall + Kylie', 'KendallKylie'),
       ('Kennel & Schmenger', 'KennelSchmenger'),
       ('Kenneth Cole', 'KennethCole'),
       ('Kenneth Cole Reaction', 'KennethColeReaction'),
       ('Kenneth Jay Lane', 'KennethJayLane'),
       ('Kent & Curwen', 'KentCurwen'),
       ('KESPER', 'KESPER'),
       ('Khaadi', 'Khaadi'),
       ('Khaite', 'Khaite'),
       ('Ki6? Who are you?', 'Ki6?Whoareyou?'),
       ('Kickers', 'Kickers'),
       ('Kidiliz', 'Kidiliz'),
       ('King Apparel', 'KingApparel'),
       ('Kipling', 'Kipling'),
       ('KitchenCraft', 'KitchenCraft'),
       ('KitonKleine Wolke', 'KitonKleineWolke'),
       ('Knot', 'Knot'),
       ('Kocca', 'Kocca'),
       ('Konstsmide', 'Konstsmide'),
       ('Kookai', 'Kookai'),
       ('Koon', 'Koon'),
       ('Koralline', 'Koralline'),
       ('Koton', 'Koton'),
       ('Koziol', 'Koziol'),
       ('Kudeta', 'Kudeta'),
       ('Kuhn Rikon', 'KuhnRikon'),
       ('Kurt Geiger', 'KurtGeiger'),
       ('L''autre Chose', 'LautreChose'),
       ('L.B.M. 1911', 'LBM1911'),
       ('L:Ú L:Ú', 'L:ÚL:Ú'),
       ('La Bonneterie Cevenole', 'LaBonneterieCevenole'),
       ('LA Linen', 'LALinen'),
       ('La Perla', 'LaPerla'),
       ('La Stupenderia', 'LaStupenderia'),
       ('La tennis Bensimon', 'LatennisBensimon'),
       ('Lacor', 'Lacor'),
       ('Lacoste', 'Lacoste'),
       ('Lamberto Losani', 'LambertoLosani'),
       ('Lands End', 'LandsEnd'),
       ('Laneus', 'Laneus'),
       ('Lanvin', 'Lanvin'),
       ('Lardini', 'Lardini'),
       ('Larusmiani', 'Larusmiani'),
       ('laviniaturra', 'laviniaturra'),
       ('Le Château', 'LeChâteau'),
       ('Le Coq Sportif', 'LeCoqSportif'),
       ('Le Mont Saint Michel', 'LeMontSaintMichel'),
       ('Le Silla', 'LeSilla'),
       ('Leather Crown', 'LeatherCrown'),
       ('Lee', 'Lee'),
       ('Lego Wear', 'LegoWear'),
       ('Leonisa', 'Leonisa'),
       ('Les Copains', 'LesCopains'),
       ('LeSportsac', 'LeSportsac'),
       ('Levi Strauss & Co.', 'LeviStraussCo'),
       ('Levi''s', 'Levis'),
       ('Liebeskind', 'Liebeskind'),
       ('LITTLE MARC JACOBS', 'LITTLEMARCJACOBS'),
       ('LittleBig', 'LittleBig'),
       ('Liu Jo', 'LiuJo'),
       ('Liviana Conti', 'LivianaConti'),
       ('Loewe', 'Loewe'),
       ('Lonely', 'Lonely'),
       ('Loro Piana', 'LoroPiana'),
       ('Lost And Found Rooms', 'LostAndFoundRooms'),
       ('Louis Philippe', 'LouisPhilippe'),
       ('Louis Vuitton', 'LouisVuitton'),
       ('Love Moschino', 'LoveMoschino'),
       ('Lovely Casa', 'LovelyCasa'),
       ('Lover', 'Lover'),
       ('Lovers + Friends', 'LoversFriends'),
       ('low brand', 'lowbrand'),
       ('Loyandford', 'Loyandford'),
       ('LSA International', 'LSAInternational'),
       ('LTB Jeans', 'LTBJeans'),
       ('Lucléon', 'Lucléon'),
       ('Luigi Borrelli', 'LuigiBorrelli'),
       ('LUIGI BORRELLI NAPOLI', 'LUIGIBORRELLINAPOLI'),
       ('Lumberjack', 'Lumberjack'),
       ('Lush Décor', 'LushDécor'),
       ('Lygia & Nanny', 'LygiaNanny'),
       ('Lyle & Scott', 'LyleScott'),
       ('M Missoni', 'MMissoni'),
       ('Macchia j', 'Macchiaj'),
       ('Madonna fashion brands', 'Madonnafashionbrands'),
       ('Magnolia Box', 'MagnoliaBox'),
       ('Maison Martin Margiela', 'MaisonMartinMargiela'),
       ('Maison Scotch', 'MaisonScotch'),
       ('Majestic Filatures', 'MajesticFilatures'),
       ('Maliparmi', 'Maliparmi'),
       ('Mallzee', 'Mallzee'),
       ('Mandarina Duck', 'MandarinaDuck'),
       ('Mangano', 'Mangano'),
       ('Mango', 'Mango'),
       ('Manila Grace', 'ManilaGrace'),
       ('Manuel Ritz', 'ManuelRitz'),
       ('Marc Jacobs', 'MarcJacobs'),
       ('Marc O''Polo', 'MarcOPolo'),
       ('Marcelo Burlon', 'MarceloBurlon'),
       ('Marco Tozzi', 'MarcoTozzi'),
       ('Maria Grazia Severi', 'MariaGraziaSeveri'),
       ('Marimekko', 'Marimekko'),
       ('Marina Rinaldi', 'MarinaRinaldi'),
       ('Marni', 'Marni'),
       ('Marsèll', 'Marsèll'),
       ('Mauro Grifoni', 'MauroGrifoni'),
       ('Mavi Jeans', 'MaviJeans'),
       ('Max Mara', 'MaxMara'),
       ('Max Studio', 'MaxStudio'),
       ('MCS', 'MCS'),
       ('Meltin Pot', 'MeltinPot'),
       ('Merc Clothing', 'MercClothing'),
       ('Merci', 'Merci'),
       ('Messagerie', 'Messagerie'),
       ('Met', 'Met'),
       ('Mexx', 'Mexx'),
       ('Michael Coal', 'MichaelCoal'),
       ('Michael Kors', 'MichaelKors'),
       ('Michael Michael Kors', 'MichaelMichaelKors'),
       ('Microbe', 'Microbe'),
       ('Mih Jeans', 'MihJeans'),
       ('Minimum', 'Minimum'),
       ('Miss Grant', 'MissGrant'),
       ('Missoni', 'Missoni'),
       ('Miu Miu', 'MiuMiu'),
       ('Miuniku', 'Miuniku'),
       ('Moncler', 'Moncler'),
       ('Monica Vinader', 'MonicaVinader'),
       ('Monnalisa', 'Monnalisa'),
       ('Moods of Norway', 'MoodsofNorway'),
       ('Morgan', 'Morgan'),
       ('Morphsuits', 'Morphsuits'),
       ('MoschinoMsgm', 'MoschinoMsgm'),
       ('Mudd Jeans', 'MuddJeans'),
       ('Muddy Puddles', 'MuddyPuddles'),
       ('Mustang', 'Mustang'),
       ('Myths', 'Myths'),
       ('N.Peal', 'NPeal'),
       ('Nafnaf', 'Nafnaf'),
       ('Nakkna', 'Nakkna'),
       ('Name It', 'NameIt'),
       ('Nanán', 'Nanán'),
       ('Napapijri', 'Napapijri'),
       ('Natasha Zinko', 'NatashaZinko'),
       ('Naturino', 'Naturino'),
       ('NBD', 'NBD'),
       ('Neck & Neck', 'NeckNeck'),
       ('Neil Barrett', 'NeilBarrett'),
       ('Neill Katter', 'NeillKatter'),
       ('New Balance', 'NewBalance'),
       ('New Era', 'NewEra'),
       ('New Look', 'NewLook'),
       ('New York Industrie', 'NewYorkIndustrie'),
       ('Nicholas Kirkwood', 'NicholasKirkwood'),
       ('Nike', 'Nike'),
       ('Nila & Nila', 'NilaNila'),
       ('Nili Lotan', 'NiliLotan'),
       ('Nina RicciNine In The Morning', 'NinaRicciNineInTheMorning'),
       ('Nixon', 'Nixon'),
       ('No Ka''Oi', 'NoKaOi'),
       ('No Secrets World', 'NoSecretsWorld'),
       ('NOBODINOZ', 'NOBODINOZ'),
       ('Noir', 'Noir'),
       ('Noisy May', 'NoisyMay'),
       ('Noko Jeans', 'NokoJeans'),
       ('Nolita Lace', 'NolitaLace'),
       ('Noppies', 'Noppies'),
       ('Nora Barth', 'NoraBarth'),
       ('Norma Kamali', 'NormaKamali'),
       ('NORMANN COPENHAGEN', 'NORMANNCOPENHAGEN'),
       ('Norse Projects', 'NorseProjects'),
       ('North Sails', 'NorthSails'),
       ('Notch', 'Notch'),
       ('Nouvelles Images', 'NouvellesImages'),
       ('NR Rapisardi', 'NRRapisardi'),
       ('Nude', 'Nude'),
       ('Nudie Jeans', 'NudieJeans'),
       ('Numero 74', 'Numero74'),
       ('N°21', 'N°21'),
       ('Nümph', 'Nümph'),
       ('O.X.S.', 'OXS'),
       ('Oakley', 'Oakley'),
       ('Oaks', 'Oaks'),
       ('Oaks Lighting', 'OaksLighting'),
       ('OAMC', 'OAMC'),
       ('ObeyOBLIQUE CREATIONS', 'ObeyOBLIQUECREATIONS'),
       ('OBVIOUS BASIC', 'OBVIOUSBASIC'),
       ('Odd Molly', 'OddMolly'),
       ('Odi Et Amo', 'OdiEtAmo'),
       ('Off-white', 'Off-white'),
       ('Office Hippo', 'OfficeHippo'),
       ('Officina 36', 'Officina36'),
       ('Officine Creative', 'OfficineCreative'),
       ('Officine Creative Italia', 'OfficineCreativeItalia'),
       ('Officine Generale', 'OfficineGenerale'),
       ('OGGI', 'OGGI'),
       ('Oilily', 'Oilily'),
       ('Oliver Peoples', 'OliverPeoples'),
       ('Olsen', 'Olsen'),
       ('OLYMPIAH', 'OLYMPIAH'),
       ('OnePiece', 'OnePiece'),
       ('Ong Shunmugam', 'OngShunmugam'),
       ('Onia', 'Onia'),
       ('Only', 'Only'),
       ('Only & Sons', 'OnlySons'),
       ('Ontour', 'Ontour'),
       ('Opening Ceremony', 'OpeningCeremony'),
       ('OPUS', 'OPUS'),
       ('Orca', 'Orca'),
       ('Orciani', 'Orciani'),
       ('Original Penguin', 'OriginalPenguin'),
       ('Original Vintage Style', 'OriginalVintageStyle'),
       ('Orlebar Brown', 'OrlebarBrown'),
       ('Oroscuro', 'Oroscuro'),
       ('Oscar De La Renta', 'OscarDeLaRenta'),
       ('Osklen', 'Osklen'),
       ('Osman', 'Osman'),
       ('Osram', 'Osram'),
       ('ottod´Ame', 'ottod´Ame'),
       ('Our Legacy', 'OurLegacy'),
       ('Ovye By Cristina Lucchi', 'OvyeByCristinaLucchi'),
       ('Oxo', 'Oxo'),
       ('P.A.R.O.S.H.', 'PAROSH'),
       ('Pal Zileri', 'PalZileri'),
       ('Palm Angels', 'PalmAngels'),
       ('Paloma Barceló', 'PalomaBarceló'),
       ('Pantaloni Torino', 'PantaloniTorino'),
       ('Pantofola D''oro', 'PantofolaDoro'),
       ('Paola Frani', 'PaolaFrani'),
       ('Paolo Pecora', 'PaoloPecora'),
       ('Paoloni', 'Paoloni'),
       ('Patrizia Pepe', 'PatriziaPepe'),
       ('Paul & Joe', 'PaulJoe'),
       ('Paul Smith', 'PaulSmith'),
       ('Paule Ka', 'PauleKa'),
       ('Pendleton Woolen Mills', 'PendletonWoolenMills'),
       ('Pennyblack', 'Pennyblack'),
       ('People', 'People'),
       ('Pepe Jeans', 'PepeJeans'),
       ('Pepe Jeans London', 'PepeJeansLondon'),
       ('PESERICO', 'PESERICO'),
       ('Peter Hahn', 'PeterHahn'),
       ('Peter Pilotto', 'PeterPilotto'),
       ('Petit Bateau', 'PetitBateau'),
       ('Peuterey', 'Peuterey'),
       ('Philipp Plein', 'PhilippPlein'),
       ('Philippe Model', 'PhilippeModel'),
       ('Philips', 'Philips'),
       ('Philosophy di Lorenzo Serafini', 'PhilosophydiLorenzoSerafini'),
       ('Pianurastudio', 'Pianurastudio'),
       ('Pieces', 'Pieces'),
       ('Pierre Hardy', 'PierreHardy'),
       ('Pingoo Prints', 'PingooPrints'),
       ('Pinko', 'Pinko'),
       ('Plein Sport', 'PleinSport'),
       ('Plein Sud', 'PleinSud'),
       ('Police', 'Police'),
       ('Pollini', 'Pollini'),
       ('Polly Flinders', 'PollyFlinders'),
       ('Polo Ralph Lauren', 'PoloRalphLauren'),
       ('Prada', 'Prada'),
       ('Preen', 'Preen'),
       ('Premiata', 'Premiata'),
       ('Premier Housewares', 'PremierHousewares'),
       ('Proenza Schouler', 'ProenzaSchouler'),
       ('Project D', 'ProjectD'),
       ('PT01', 'PT01'),
       ('Puma', 'Puma'),
       ('Q/S designed by', 'QSdesignedby'),
       ('Q/S designed by - s.Oliver', 'QSdesignedby-sOliver'),
       ('Q1', 'Q1'),
       ('Q2', 'Q2'),
       ('Qasimi', 'Qasimi'),
       ('Qcqc', 'Qcqc'),
       ('Qdo', 'Qdo'),
       ('Qed London', 'QedLondon'),
       ('QEEBOO', 'QEEBOO'),
       ('Ql2 Quelledue', 'Ql2Quelledue'),
       ('Qu4ttro', 'Qu4ttro'),
       ('Quail', 'Quail'),
       ('Qualy', 'Qualy'),
       ('Quantum Courage', 'QuantumCourage'),
       ('QUATTRO.DECIMI', 'QUATTRODECIMI'),
       ('Quattrobarradodici', 'Quattrobarradodici'),
       ('Quax', 'Quax'),
       ('Quay Eyeware', 'QuayEyeware'),
       ('Quayside', 'Quayside'),
       ('Queen', 'Queen'),
       ('Queen Bee', 'QueenBee'),
       ('Queen Mum', 'QueenMum'),
       ('Queen Of Love', 'QueenOfLove'),
       ('Queene and Belle', 'QueeneandBelle'),
       ('Queens', 'Queens'),
       ('Queensway', 'Queensway'),
       ('Querini', 'Querini'),
       ('Quest', 'Quest'),
       ('Quetsche', 'Quetsche'),
       ('Quid', 'Quid'),
       ('Quiksilver', 'Quiksilver'),
       ('Quintessence', 'Quintessence'),
       ('QUIS QUIS', 'QUISQUIS'),
       ('Quiz', 'Quiz'),
       ('Quoddy', 'Quoddy'),
       ('Quodlibet', 'Quodlibet'),
       ('Qupid', 'Qupid'),
       ('QURE', 'QURE'),
       ('Quttin', 'Quttin'),
       ('R13', 'R13'),
       ('Rag & Bone', 'RagBone'),
       ('Rajrang', 'Rajrang'),
       ('Ralph Lauren', 'RalphLauren'),
       ('Raoul', 'Raoul'),
       ('Ray-Ban', 'Ray-Ban'),
       ('RBV BIRKMANN', 'RBVBIRKMANN'),
       ('Re-hash', 'Re-hash'),
       ('Re/Done', 'ReDone'),
       ('Real Gold', 'RealGold'),
       ('Rebecca Minkoff', 'RebeccaMinkoff'),
       ('Red Valentino', 'RedValentino'),
       ('Red(v)', 'Red(v)'),
       ('Reebok', 'Reebok'),
       ('Reflect-please', 'Reflect-please'),
       ('RefrigiWear', 'RefrigiWear'),
       ('Reiss', 'Reiss'),
       ('Relaxdays', 'Relaxdays'),
       ('Religion', 'Religion'),
       ('Relish', 'Relish'),
       ('Renaissance 2000', 'Renaissance2000'),
       ('Replay', 'Replay'),
       ('Rick Owens', 'RickOwens'),
       ('Rieker', 'Rieker'),
       ('Rip Curl', 'RipCurl'),
       ('Riva Paoletti', 'RivaPaoletti'),
       ('River Island', 'RiverIsland'),
       ('Robert Clergerie', 'RobertClergerie'),
       ('Roberto Cavalli', 'RobertoCavalli'),
       ('Roberto Collina', 'RobertoCollina'),
       ('Roberto Festa Milano', 'RobertoFestaMilano'),
       ('Rochas', 'Rochas'),
       ('Roda', 'Roda'),
       ('Rodo', 'Rodo'),
       ('Roger Vivier', 'RogerVivier'),
       ('Roksanda Ilincic', 'RoksandaIlincic'),
       ('Roland Mouret', 'RolandMouret'),
       ('Rosasen', 'Rosasen'),
       ('Rossopuro', 'Rossopuro'),
       ('Roy Rogers', 'RoyRogers'),
       ('Royal Republiq', 'RoyalRepubliq'),
       ('Rta', 'Rta'),
       ('Ruco Line', 'RucoLine'),
       ('Rufskin', 'Rufskin'),
       ('Rêve En Vert', 'RêveEnVert'),
       ('S.E.H Kelly', 'SEHKelly'),
       ('s.Oliver', 'sOliver'),
       ('SABA', 'SABA'),
       ('sacai', 'sacai'),
       ('Saint Laurent', 'SaintLaurent'),
       ('Saint Tropez', 'SaintTropez'),
       ('Sakis Rouvas Collection', 'SakisRouvasCollection'),
       ('Salvatore Ferragamo', 'SalvatoreFerragamo'),
       ('Salvatore Ferragamo S.p.A.', 'SalvatoreFerragamoSpA'),
       ('Sanetta', 'Sanetta'),
       ('Santoni', 'Santoni'),
       ('Schiesser', 'Schiesser'),
       ('Schutz', 'Schutz'),
       ('Scotch & Soda', 'ScotchSoda'),
       ('Scotch and Soda', 'ScotchandSoda'),
       ('See By Chloé', 'SeeByChloé'),
       ('Selected', 'Selected'),
       ('Sendmeamirror', 'Sendmeamirror'),
       ('Sergio Rossi', 'SergioRossi'),
       ('Seventy', 'Seventy'),
       ('Shiatzy Chen', 'ShiatzyChen'),
       ('Silver Jeans Co.', 'SilverJeansCo'),
       ('Silvian Heach', 'SilvianHeach'),
       ('Simonetta', 'Simonetta'),
       ('SINOIAN', 'SINOIAN'),
       ('Siviglia', 'Siviglia'),
       ('Six Deuce', 'SixDeuce'),
       ('Sixpack France', 'SixpackFrance'),
       ('Skechers', 'Skechers'),
       ('Snobby Sheep', 'SnobbySheep'),
       ('Soleil d''Ocre', 'SoleildOcre'),
       ('Sonia Rykiel', 'SoniaRykiel'),
       ('Sophie Paris Vietnam', 'SophieParisVietnam'),
       ('Space Style Concept', 'SpaceStyleConcept'),
       ('Springfield', 'Springfield'),
       ('Star in the Hood', 'StarintheHood'),
       ('Star Wars', 'StarWars'),
       ('Starworld', 'Starworld'),
       ('Stefanel', 'Stefanel'),
       ('Stella McCartney', 'StellaMcCartney'),
       ('Sterntaler', 'Sterntaler'),
       ('Steve Madden', 'SteveMadden'),
       ('Stick It On Your Wall', 'StickItOnYourWall'),
       ('Street One', 'StreetOne'),
       ('Strellson', 'Strellson'),
       ('Stuart Weitzman', 'StuartWeitzman'),
       ('Stupell Industries', 'StupellIndustries'),
       ('Sun 68', 'Sun68'),
       ('Sundek', 'Sundek'),
       ('Suoli', 'Suoli'),
       ('Super Cool Creations', 'SuperCoolCreations'),
       ('Superdry', 'Superdry'),
       ('Superga', 'Superga'),
       ('Swear', 'Swear'),
       ('T-fal', 'T-fal'),
       ('Tagliatore', 'Tagliatore'),
       ('Taifun', 'Taifun'),
       ('Takeo Kikuchi', 'TakeoKikuchi'),
       ('Tally WeijlTamaki niime', 'TallyWeijlTamakiniime'),
       ('Tamaris', 'Tamaris'),
       ('Tarocash', 'Tarocash'),
       ('Ted Baker', 'TedBaker'),
       ('Tescoma', 'Tescoma'),
       ('The Art Group', 'TheArtGroup'),
       ('The Fashion Bible', 'TheFashionBible'),
       ('The Oliver Gal Artist Co.', 'TheOliverGalArtistCo'),
       ('The Row', 'TheRow'),
       ('The Stupell Home Décor Collection', 'TheStupellHomeDécorCollection'),
       ('Theory', 'Theory'),
       ('Think', 'Think'),
       ('Thom Browne', 'ThomBrowne'),
       ('Thomas Sabo', 'ThomasSabo'),
       ('Three Gun', 'ThreeGun'),
       ('Tibi', 'Tibi'),
       ('Tiffany & Co.', 'TiffanyCo'),
       ('Tiger of Sweden', 'TigerofSweden'),
       ('Tigha', 'Tigha'),
       ('Timberland', 'Timberland'),
       ('TNT', 'TNT'),
       ('Tod''s', 'Tods'),
       ('Tom Ford', 'TomFord'),
       ('Tom Tailor', 'TomTailor'),
       ('Tombolini', 'Tombolini'),
       ('Tommy Hilfiger', 'TommyHilfiger'),
       ('Tommy Jeans', 'TommyJeans'),
       ('Tonello', 'Tonello'),
       ('Tony Rubino', 'TonyRubino'),
       ('Tory Burch', 'ToryBurch'),
       ('Tosca Blu', 'ToscaBlu'),
       ('Toy G', 'ToyG'),
       ('Trands', 'Trands'),
       ('Trendhim', 'Trendhim'),
       ('Trio Leuchten', 'TrioLeuchten'),
       ('Triumph', 'Triumph'),
       ('True Religion', 'TrueReligion'),
       ('Truenyc', 'Truenyc'),
       ('Trussardi', 'Trussardi'),
       ('Twin-Set', 'Twin-Set'),
       ('Twisted Envy', 'TwistedEnvy'),
       ('U.S.Polo Association', 'USPoloAssociation'),
       ('UCLIC', 'UCLIC'),
       ('UGG', 'UGG'),
       ('Ugo Cacciatori', 'UgoCacciatori'),
       ('Ulla Johnson', 'UllaJohnson'),
       ('Ulla Popken', 'UllaPopken'),
       ('Ultra Chic', 'UltraChic'),
       ('Ultracor', 'Ultracor'),
       ('Uma', 'Uma'),
       ('Uma Wang', 'UmaWang'),
       ('Umbra', 'Umbra'),
       ('Umbro', 'Umbro'),
       ('Umd', 'Umd'),
       ('Umit Benan', 'UmitBenan'),
       ('Un-Namable', 'Un-Namable'),
       ('Unconditional', 'Unconditional'),
       ('Under Armour', 'UnderArmour'),
       ('Undercover', 'Undercover'),
       ('Uniform', 'Uniform'),
       ('Uniform Wares', 'UniformWares'),
       ('Unique21', 'Unique21'),
       ('Unisa', 'Unisa'),
       ('United Curtain Co.', 'UnitedCurtainCo'),
       ('United Nude', 'UnitedNude'),
       ('Unity', 'Unity'),
       ('Universal Works', 'UniversalWorks'),
       ('UNKL347', 'UNKL347'),
       ('UNLACE', 'UNLACE'),
       ('Unlimited', 'Unlimited'),
       ('Unravel', 'Unravel'),
       ('Unze', 'Unze'),
       ('Unützer', 'Unützer'),
       ('Uomolebole', 'Uomolebole'),
       ('Up Jeans', 'UpJeans'),
       ('Up To Be', 'UpToBe'),
       ('Urban Classic', 'UrbanClassic'),
       ('Urban Code', 'UrbanCode'),
       ('URBAN LES HOMMES', 'URBANLESHOMMES'),
       ('Urban Male', 'UrbanMale'),
       ('Uta Raasch', 'UtaRaasch'),
       ('Vagabond', 'Vagabond'),
       ('Valentino', 'Valentino'),
       ('Valextra', 'Valextra'),
       ('Vallila', 'Vallila'),
       ('Vanessa Bruno', 'VanessaBruno'),
       ('Vanessa Scott', 'VanessaScott'),
       ('Vans', 'Vans'),
       ('VB Rocks', 'VBRocks'),
       ('VDP Collection', 'VDPCollection'),
       ('Velvet', 'Velvet'),
       ('Vent du Sud', 'VentduSud'),
       ('Vero Moda', 'VeroModa'),
       ('VERSA', 'VERSA'),
       ('Versace', 'Versace'),
       ('Versace Jeans Couture', 'VersaceJeansCouture'),
       ('Versus', 'Versus'),
       ('VETEMENTS', 'VETEMENTS'),
       ('Via Appia Due', 'ViaAppiaDue'),
       ('Vic Matié', 'VicMatié'),
       ('Vicini', 'Vicini'),
       ('Vicolo', 'Vicolo'),
       ('Victoria', 'Victoria'),
       ('Victoria Beckham', 'VictoriaBeckham'),
       ('VIDA', 'VIDA'),
       ('Viking', 'Viking'),
       ('Vila', 'Vila'),
       ('VilebrequinVilla D''Este Home Tivoli', 'VilebrequinVillaDEsteHomeTivoli'),
       ('Villeroy & Boch', 'VilleroyBoch'),
       ('VILSHENKO', 'VILSHENKO'),
       ('Vince', 'Vince'),
       ('Vingino', 'Vingino'),
       ('Vintage De Luxe', 'VintageDeLuxe'),
       ('Vionnet', 'Vionnet'),
       ('Visvim', 'Visvim'),
       ('Vivance', 'Vivance'),
       ('Vivetta', 'Vivetta'),
       ('Vivienne Westwood', 'VivienneWestwood'),
       ('Vix', 'Vix'),
       ('Vneck', 'Vneck'),
       ('W118 by Walter Baker', 'W118byWalterBaker'),
       ('Waldläufer', 'Waldläufer'),
       ('Wall Art', 'WallArt'),
       ('Wall Smart Designs', 'WallSmartDesigns'),
       ('Wallis', 'Wallis'),
       ('Walplus', 'Walplus'),
       ('Walter Baker', 'WalterBaker'),
       ('Walther Design', 'WaltherDesign'),
       ('Warehouse', 'Warehouse'),
       ('Wash+Dry', 'WashDry'),
       ('Weekday', 'Weekday'),
       ('Weili Zheng', 'WeiliZheng'),
       ('WENKO', 'WENKO'),
       ('WESC', 'WESC'),
       ('WESCO', 'WESCO'),
       ('Westmark', 'Westmark'),
       ('What For', 'WhatFor'),
       ('Whats On Your Wall', 'WhatsOnYourWall'),
       ('Wheat', 'Wheat'),
       ('White Mountaineering', 'WhiteMountaineering'),
       ('White Sand 88', 'WhiteSand88'),
       ('White Stuff Clothing', 'WhiteStuffClothing'),
       ('Who*s Who', 'Who*sWho'),
       ('Whyred', 'Whyred'),
       ('Wildfox', 'Wildfox'),
       ('Wilton', 'Wilton'),
       ('Windsor Smith', 'WindsorSmith'),
       ('Wise Guy', 'WiseGuy'),
       ('WMF', 'WMF'),
       ('Wofi Leuchten', 'WofiLeuchten'),
       ('Wolford', 'Wolford'),
       ('Women''secret', 'Womensecret'),
       ('Won Hundred', 'WonHundred'),
       ('Wood Wood', 'WoodWood'),
       ('Woodwick', 'Woodwick'),
       ('Wool & Co', 'WoolCo'),
       ('Woolrich', 'Woolrich'),
       ('Wrangler', 'Wrangler'),
       ('Wtr London', 'WtrLondon'),
       ('Wyldr', 'Wyldr'),
       ('Wåven', 'Wåven'),
       ('X Bionic', 'XBionic'),
       ('X by NBD', 'XbyNBD'),
       ('X Loop', 'XLoop'),
       ('X Socks', 'XSocks'),
       ('X&B XAVEM', 'XBXAVEM'),
       ('X-Cape', 'X-Cape'),
       ('Xacus', 'Xacus'),
       ('Xagon Man', 'XagonMan'),
       ('Xander Zhou', 'XanderZhou'),
       ('Xandres', 'Xandres'),
       ('XAVAX', 'XAVAX'),
       ('Xavier Danaud', 'XavierDanaud'),
       ('XBAKKO', 'XBAKKO'),
       ('XBRAND', 'XBRAND'),
       ('Xc-Xacaret', 'Xc-Xacaret'),
       ('XConcept', 'XConcept'),
       ('Xenia', 'Xenia'),
       ('XENIA BOUS', 'XENIABOUS'),
       ('Xia Home Fashions', 'XiaHomeFashions'),
       ('Ximena Kavalekas', 'XimenaKavalekas'),
       ('Xirena', 'Xirena'),
       ('Xoos', 'Xoos'),
       ('Xs Milano', 'XsMilano'),
       ('Xsensible', 'Xsensible'),
       ('Xti', 'Xti'),
       ('Xtreme', 'Xtreme'),
       ('XTSY', 'XTSY'),
       ('XX Coss Concept', 'XXCossConcept'),
       ('Xyxyx', 'Xyxyx'),
       ('XZX-Star', 'XZX-Star'),
       ('Y / Project', 'YProject'),
       ('Y.A.S', 'YAS'),
       ('Y.A.S.', 'YAS'),
       ('Y.A.S. Tall', 'YASTall'),
       ('YAB', 'YAB'),
       ('Yan Simmon', 'YanSimmon'),
       ('Yang Li', 'YangLi'),
       ('Yankee Candle Company', 'YankeeCandleCompany'),
       ('Yasmine Eslami', 'YasmineEslami'),
       ('Yeezy by Kanye West', 'YeezybyKanyeWest'),
       ('Yellow Cab', 'YellowCab'),
       ('Yep', 'Yep'),
       ('Yeprem', 'Yeprem'),
       ('Yerse', 'Yerse'),
       ('Yes London', 'YesLondon'),
       ('Yes-Zee', 'Yes-Zee'),
       ('Yigal AzrouËl', 'YigalAzrouËl'),
       ('Ylati', 'Ylati'),
       ('Ymc You Must Create', 'YmcYouMustCreate'),
       ('Yohji Yamamoto', 'YohjiYamamoto'),
       ('Yoko Design', 'YokoDesign'),
       ('Yoon', 'Yoon'),
       ('YOSHII', 'YOSHII'),
       ('Yosi Samra', 'YosiSamra'),
       ('Yosuzi', 'Yosuzi'),
       ('Young Versace', 'YoungVersace'),
       ('Your Turn', 'YourTurn'),
       ('Yours Clothing', 'YoursClothing'),
       ('YPNO', 'YPNO'),
       ('YPORQUÉ', 'YPORQUÉ'),
       ('Yshey', 'Yshey'),
       ('Yuliya Magdych', 'YuliyaMagdych'),
       ('Yumi', 'Yumi'),
       ('Yumi Kim', 'YumiKim'),
       ('Yummie Tummie', 'YummieTummie'),
       ('Yuul Yie', 'YuulYie'),
       ('Yuzefi', 'Yuzefi'),
       ('Yves Salomon', 'YvesSalomon'),
       ('Yvonne Léon', 'YvonneLéon'),
       ('Zac Posen', 'ZacPosen'),
       ('Zack', 'Zack'),
       ('Zadig & Voltaire', 'ZadigVoltaire'),
       ('Zaida', 'Zaida'),
       ('Zak designs', 'Zakdesigns'),
       ('Zanella', 'Zanella'),
       ('Zanellato', 'Zanellato'),
       ('Zanetti', 'Zanetti'),
       ('Zanetti 1965', 'Zanetti1965'),
       ('Zanfrini', 'Zanfrini'),
       ('Zanieri', 'Zanieri'),
       ('Zanone', 'Zanone'),
       ('Zassenhaus', 'Zassenhaus'),
       ('Zeal', 'Zeal'),
       ('Zebra', 'Zebra'),
       ('ZEBRA TEXTIL', 'ZEBRATEXTIL'),
       ('Zeferino', 'Zeferino'),
       ('ZELLER', 'ZELLER'),
       ('Zenker', 'Zenker'),
       ('Zenobi', 'Zenobi'),
       ('ZEP', 'ZEP'),
       ('Zero + Maria Cornejo', 'ZeroMariaCornejo'),
       ('Zero Construction', 'ZeroConstruction'),
       ('Zeus + Dione', 'ZeusDione'),
       ('Zeynep Arcay', 'ZeynepArcay'),
       ('Zhelda', 'Zhelda'),
       ('Ziggy Chen', 'ZiggyChen'),
       ('Zilverstad', 'Zilverstad'),
       ('Zimmerli', 'Zimmerli'),
       ('Zimmermann', 'Zimmermann'),
       ('Zinda', 'Zinda'),
       ('Zippo', 'Zippo'),
       ('Zippy', 'Zippy'),
       ('Zizzi', 'Zizzi'),
       ('Zoe Karssen', 'ZoeKarssen'),
       ('Zucca', 'Zucca'),
       ('Zuhair Murad', 'ZuhairMurad'),
       ('Zwilling', 'Zwilling'),
       ('Zyliss', 'Zyliss');